Ders6/Models/EmailModel.cs
namespace Ders6.Models
{
    public class EmailModel
    {
        public string ToEmail { get; set; }
        public string Subject { get; set; }

        public string Body { get; set; }
    }
}

Ders6/Models/ErrorViewModel.cs
namespace Ders6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ders6/Models/RandomPasswordGenerator.cs
namespace Ders6.Models
{
    public class RandomPasswordGenerator
    {
        public string Password { get; set; }
        public string HashedPassword { get; set; }
        public DateTime GenerateDate { get; set; }

    }
}

Ders6/Models/Town.cs
namespace Ders6.Models
{
    public class Town
    {
        public string Name { get; set; }

    }
}

Ders6/Models/WeatherInfo.cs
namespace Ders6.Models
{
    public class WeatherInfo
    {
        public string City { get; set; }
        public string Temperature { get; set; }
        public string Description { get; set; }

    }
}

Ders6/Controllers/HomeController.cs
using Ders6.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Ders6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            if (HttpContext.Session.GetString("username") == null){

                return RedirectToAction("Index", "Login");
            }

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ders6/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ders6.Controllers
{
    public class LoginController : Controller
    {
        private const string Username = "admin";
        private const string Password = "12345a";
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string username,string password)
        {
            if (username == Username && password == Password)
            {
                HttpContext.Session.SetString("username", username);
                return RedirectToAction("Index", "Home");

            }

            ViewBag.message = "Hatalı kullanıcı adı ve şifre";


            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("Index", "Login");
        }
   }
}

Ders6/Controllers/MailController.cs
using Ders6.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace Ders6.Controllers
{
    public class MailController : Controller
    {
        //Gmail Smtp Ayarları

        private readonly string smtpAddress = "smtp.gmail.com";
        private readonly int portNumber = 587;
        private readonly bool enableSSL = true;
        private readonly string FromEmail = "zeusaku27@gmail.com";
        private readonly string Password = "admin246";


        public IActionResult Index()
        {



            return View();
        }

        [HttpPost]
        public IActionResult SendMail(EmailModel model)
        {
            try
            {

                var SmtpClient = new SmtpClient(smtpAddress)
                {
                    Port=portNumber,
                    Credentials=new NetworkCredential(FromEmail,Password),
                    EnableSsl= enableSSL

                };


                var mailMessage = new MailMessage
                {

                    From = new MailAddress(FromEmail),
                    Subject=model.Subject,
                    Body = model.Body,
                    IsBodyHtml=true


                };

                mailMessage.To.Add(model.ToEmail);
                SmtpClient.Send(mailMessage);
                ViewBag.message = "Email Başarıyla Gönderildi";
                

            }
            catch (Exception ex)
            {
                ViewBag.message = "Email Hata Meydana Geldi"+ex.ToString();


            }


            return View("Index");
        }



    }
}

Ders6/Controllers/PasswordController.cs
using Ders6.Models;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Text;
using System.Security.Cryptography;


namespace Ders6.Controllers
{
    public class PasswordController : Controller
    {
        private static readonly string FilePath = "password.txt";
        public IActionResult Index()
        {



            return View();
        }

        [HttpPost]
        public IActionResult Generate()
        {
            var passwordModel = new RandomPasswordGenerator
            {
                Password=GenerateRandomPassword(12),//rastgele şifre oluştur
                HashedPassword=HashPassword(GenerateRandomPassword(12)),
                GenerateDate=DateTime.Now
            };


            SavePassword(passwordModel);



            return View("Index",passwordModel);
        }

        //Random Password Oluştur
        private string GenerateRandomPassword(int length)
        {
            const string validchar = "ABCDEFERTYUIOPSDFGHJKLŞŞXCBNMÖMÖ123465789";
            StringBuilder res = new StringBuilder();

            using (RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider())
            {
                byte[] uintBuffer = new byte[sizeof(uint)];

                while (length-- > 0)
                {
                    rng.GetBytes(uintBuffer);
                    uint num = BitConverter.ToUInt32(uintBuffer, 0);
                    res.Append(validchar[(int)(num % (uint)validchar.Length)]);
                }
            }
            return res.ToString();
        }

        private string HashPassword(string password)
        {

            using(SHA256 sha256Hash=SHA256.Create())
            {

                byte[]bytes=sha256Hash.ComputeHash(Encoding.UTF8.GetBytes(password));
                StringBuilder builder=new StringBuilder();
                for (int i = 0; i < bytes.Length; i++)
                {
                    builder.Append(bytes[i].ToString("x2"));
                }
                return builder.ToString();
            }

        }


        private void SavePassword(RandomPasswordGenerator passwordModel)
        {
            string data = $"{passwordModel.Password},{passwordModel.HashedPassword},{passwordModel.GenerateDate}\n";
            System.IO.File.AppendAllText(FilePath, data);
        }
    }
}

Ders6/ViewComponents/SimpleMessageViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Ders6.ViewComponents
{
    public class SimpleMessageViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            string message = "Merhaba Ben View Component Kullanmayı Öğrendim";

            return View("Default",message);
        }

    }
}

Ders6/ViewComponents/TownsViewComponent.cs
using Ders6.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ders6.ViewComponents
{
    public class TownsViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var tw = new List<Town>
            {

                new Town{Name="Adalar"},
                new Town{Name="Beşiktaş"},
                new Town{Name="Kadıköy"},
                new Town{Name="Maltepe"},
                new Town{Name="Eyüpsultan"},
                new Town{Name="Bakırköy"},
                new Town{Name="Zeytinburnu"}

            };

            return View(tw);
        }

    }
}

Ders6/ViewComponents/WeatherViewComponent.cs
using Ders6.Models;
using Microsoft.AspNetCore.Mvc;

namespace Ders6.ViewComponents
{
    public class WeatherViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            var vt = new WeatherInfo
            {
                City = "İstanbul",
                Temperature = "25 C",
                Description = "Guneşli"


            };

            return View(vt);
        }
    }
}

Ders6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


@await Component.InvokeAsync("Weather")
<hr />
<br />

@await Component.InvokeAsync("Towns")

Ders6/Views/Login/Index.cshtml
<h2>Login Giriş Sayfası</h2>





<form asp-controller="Login" asp-action="Index" method="post">


    <div>
        <label for="username">Kullanıcı Adı: </label>
        <input type="text" id="username" name="username" required />
    </div>


    <div>
        <label for="password">Şifre: </label>
        <input type="password" id="password" name="password" required />
    </div>

    <button type="submit">Login</button>

</form>


@await Component.InvokeAsync("SimpleMessage")

@if (ViewBag.message!=null)
{
    <p class="alert alert-danger">ViewBag.message</p>
    
}

Ders6/Views/Password/Index.cshtml
@model RandomPasswordGenerator


<div class="container">


    <h2>Random Şifre Oluşturma Ekranı</h2>
    <p>Random oluştur ve txt dosyasına kaydet</p>

    <form asp-action="Generate" method="post" class="mt-5">

        <button type="submit" class="btn btn-primary">Random Şifre Oluştur</button>


    </form>


    @if(Model!=null)
    {
        <div class="mt-3">

            <h2>Random Şifre: <span class="text-success">@Model.Password</span></h2>
            <h2>Hash Şifre: <span class="text-info">@Model.HashedPassword</span></h2>
            <h2>Oluşturma Tarihi : <span class="text-primary">@Model.GenerateDate</span></h2>


        </div>
        
    }


</>

Ders6/Views/Shared/Components/SimpleMessage/Default.cshtml
@model string

<div >
    <p>@Model</p>
</div>

Ders6/Views/Shared/Components/Towns/Default.cshtml
@model IEnumerable<Town>

 <h3>İstanbul İlçeleri</h3>

 <ul>

     @foreach (var item in Model)
    {
        <li>@item.Name</li>

    }

 </ul>

Ders6/Views/Shared/Components/Weather/Default.cshtml
@model WeatherInfo

<div >

    <h3>Şehir: @Model.City</h3>
    <p>Sıcaklık: @Model.Temperature</p>
    <p>Açıklama: @Model.Description</p>

</div>

Ders6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ders6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ders6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ders6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ders6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>